spring.application.name=api_thuoc
spring.datasource.url=jdbc:mysql://localhost:3306/tracking_order?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
server.port=7081
logging.level.root=DEBUG
logging.level.org.springframework.security=DEBUG
